version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${git.build.user.name}
builderEmail=${git.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${git.branch}
gitCommitIdDescribe=${git.commit.id.describe}
gitCommitId=${git.commit.id.full}
gitCommitUrl=${git.remote.origin.url}
gitCommitTime=${git.commit.time}
gitDirty=${git.dirty}
