#==================================================
#   L O G G I N G
# Logging file (for errors, info ...)
# Defined in a separate property file according to java.util.logging.LogManager
# Must be accessible by class loder (may be put in src/main/java folder)
logManager.properties.file=loggingProperties.properties

# Formatter for specific handlers (GUI logging, custom formatter)
# Available Formatters
#   java.util.logging.SimpleFormatter
#   java.util.logging.XMLFormatter
#   org.fl.util.PlainLogFormatter
#   org.fl.util.JsonLogFormatter
logging.formatter=org.fl.util.PlainLogFormatter
#==================================================
# S W I N G   G U I

appTabbedPane.logging.lastNonHighLighedLevel=INFO
appTabbedPane.logging.recordHighLightColor=PINK
appTabbedPane.logging.logTabHighLightColor=RED

appTabbedPane.logging.logDisplayMaxLength=100000
appTabbedPane.logging.subTabNumber=3
appTabbedPane.logging.logTabSelectedColor=GREEN
appTabbedPane.logging.searchHighLightColors=CYAN,LIGHT_GRAY,YELLOW,MAGENTA
#==================================================

webAppli.configurationFile=skeletonApi.properties
#webAppli.configurationFile=knowWho.properties
#webAppli.configurationFile=skyLineApi.properties
#webAppli.configurationFile=iocProxyApi.properties
#webAppli.configurationFile=cognitiveSearch.properties
